version: '3.2'
services:
  react-app:
    image: bbshelf.azurecr.io/react-app:latest
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - mongo
      - node-app
    volumes:
      - ./static:/usr/share/nginx/static
  node-app:
    image: bbshelf.azurecr.io/node-app:latest
    build: ./server
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    volumes:
      - ./static:/usr/src/app/static
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/bbshelf
      - MONGO_URL_TESTS=mongodb://mongo:27017/bbshelf-test
      - COMPOSE=true
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

volumes:
  static:
  dbdata:
