version: '3'
services:
  react-app:
    build: ./client
    ports:
      - '80:80'
    stdin_open: true
    depends_on:
      - node-app
  node-app:
    build: ./server
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/bbshelf
      - MONGO_URL_TESTS=mongodb://mongo:27017/bbshelf-test
      - COMPOSE=true
  mongo:
    image: mongo
    ports:
      - '27017:27017'
