version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  node-app:
    build: .
    ports:
      - '4000:4000'
    depends_on: 
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/bbshelf
      - MONGO_URL_TESTS=mongodb://mongo:27017/bbshelf-test
      - COMPOSE=true